version: "3.8"

services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - ms-network
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ms-network

  complete-api:
    build: ./complete-api
    container_name: complete-api
    ports:
      - "6000:6000"
    environment:
      - STRIPE_SECRET_KEY=sk_test_51QCRX0RpWZoKXUjjat6kO9qFZUFQDj2OWoPHRz4AO25xvoT8rgF2UG0hWkrVcXrXRdfoSLMrRPl8UUfgjHTaBFAz0077Hll99H
      - STRIPE_WH_CHECKOUT=whsec_BFvAELqOPQMXK1IEaKMgQl4MvW08ixa5
      - STRIPE_WH_CANCEL=whsec_2adS2wwof5PcDzMN4SCCaqKDjvfOlODM
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - POSTGRES_PORT=5432
      - KONG_ADMIN_URL=http://159.223.108.72:4001
    networks:
      - ms-network
    depends_on:
      - redis
      - postgresql

networks:
  ms-network:
    driver: bridge
