version: "3.8"

services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - ms-network
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ms-network

  whatsapp-api:
    build: ./whatsapp-api
    container_name: whatsapp-api
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgresql
    networks:
      - ms-network
    depends_on:
      - redis
      - postgresql

  complete-api:
    build: ./complete-api
    container_name: complete-api
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgresql
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - POSTGRES_PORT=5432
    networks:
      - ms-network
    depends_on:
      - redis
      - postgresql

networks:
  ms-network:
    driver: bridge
