version: "3.8"

services:
  complete-api:
    build: .
    container_name: complete-api
    ports:
      - "6000:6000"
    environment:
      - REDIS_HOST=scheduler_n8n-redis
      - POSTGRES_HOST=scheduler_n8n-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=c390ac090d228ee3ba4d
      - POSTGRES_DB=scheduler
      - POSTGRES_PORT=5432
      - KONG_ADMIN_URL=http://scheduler_api-gateway-kong-1:4001
